### ISSUE TITLE
[Bug]: 2FA is not required by login

### ISSUE THREAD

**Issue by laraben** [stephenjude/filament-two-factor-authentication#8]
### What happened?

Hi, i've followed all the steps and setup a 2FA.
But when i log out and log back in. It doesnt ask for the 2FA.
The first time ive logged in, it asked to setup my 2FA.
But when i log in it never ask for it

### How to reproduce the bug

Hi, i've followed all the steps and setup a 2FA.
But when i log out and log back in. It doesnt ask for the 2FA.
The first time ive logged in, it asked to setup my 2FA.
But when i log in it never ask for it

### Package Version

0.0.8

### PHP Version

8.2

### Laravel Version

11

### Which operating systems does with happen with?

macOS

### Notes

Hi, i've followed all the steps and setup a 2FA.
But when i log out and log back in. It doesnt ask for the 2FA.
The first time ive logged in, it asked to setup my 2FA.
But when i log in it never ask for it

**Comment by laraben** [comment]
ok i've found it, i had to add:
use Stephenjude\FilamentTwoFactorAuthentication\Pages\Login;

final class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->default()
            ->id('admin')
            ->path('admin')
            ->login(Login::class)

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the `authenticate` method in `Login.php` to properly handle 2FA challenge after successful login credentials validation.

I also created pull request: https://github.com/stephenjude/filament-two-factor-authentication/pull/9


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
